// Code generated by candi v1.17.15.

package graphqlhandler

import (
	"monorepo/services/library-service/pkg/shared/usecase"
	
	"github.com/golangid/candi/codebase/factory/dependency"
	"github.com/golangid/candi/codebase/interfaces"
)

// GraphQLHandler model
type GraphQLHandler struct {
	mw        interfaces.Middleware
	uc        usecase.Usecase
	validator interfaces.Validator
}

// NewGraphQLHandler delivery
func NewGraphQLHandler(uc usecase.Usecase, deps dependency.Dependency) *GraphQLHandler {
	return &GraphQLHandler{
		uc: uc, mw: deps.GetMiddleware(), validator: deps.GetValidator(),
	}
}

// Query method
func (h *GraphQLHandler) Query() interface{} {
	return h
}

// Mutation method
func (h *GraphQLHandler) Mutation() interface{} {
	return h
}

// Subscription method
func (h *GraphQLHandler) Subscription() interface{} {
	return h
}

// Schema method
func (h *GraphQLHandler) Schema() string {
	return ""
}
