// Code generated by candi v1.17.15.

package usecase

import (
	"context"

	"monorepo/services/library-service/internal/modules/reservation/domain"
	"monorepo/services/library-service/pkg/shared/repository"
	"monorepo/services/library-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// ReservationUsecase abstraction
type ReservationUsecase interface {
	GetAllReservation(ctx context.Context, filter *domain.FilterReservation) (data domain.ResponseReservationList, err error)
	GetDetailReservation(ctx context.Context, id int) (data domain.ResponseReservation, err error)
	CreateReservation(ctx context.Context, data *domain.RequestReservation) (res domain.ResponseReservation, err error) 
	UpdateReservation(ctx context.Context, data *domain.RequestReservation) (err error)
	DeleteReservation(ctx context.Context, id int) (err error)
}

type reservationUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewReservationUsecase usecase impl constructor
func NewReservationUsecase(deps dependency.Dependency) (ReservationUsecase, func(sharedUsecase common.Usecase)) {
	uc := &reservationUsecaseImpl{
		deps:    deps,
		repoSQL:   repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),
		
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
