// Code generated by candi v1.17.15.

package repository

import (
	"context"

	"monorepo/services/library-service/internal/modules/reservation/domain"
	shareddomain "monorepo/services/library-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// ReservationRepository abstract interface
type ReservationRepository interface {
	FetchAll(ctx context.Context, filter *domain.FilterReservation) ([]shareddomain.Reservation, error)
	Count(ctx context.Context, filter *domain.FilterReservation) int
	Find(ctx context.Context, filter *domain.FilterReservation) (shareddomain.Reservation, error)
	Save(ctx context.Context, data *shareddomain.Reservation, updateOptions ...candishared.DBUpdateOptionFunc)  <- chan error
	Delete(ctx context.Context, filter *domain.FilterReservation) (err error)
}
