// Code generated by candi v1.17.15.

package repository

import (
	"context"

	"strings"
	"time"

	"monorepo/services/library-service/internal/modules/reservation/domain"
	shareddomain "monorepo/services/library-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"monorepo/globalshared"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type reservationRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewReservationRepoSQL mongo repo constructor
func NewReservationRepoSQL(readDB, writeDB *gorm.DB) ReservationRepository {
	return &reservationRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *reservationRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterReservation) (data []shareddomain.Reservation, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ReservationRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterReservation(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *reservationRepoSQL) Count(ctx context.Context, filter *domain.FilterReservation) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ReservationRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterReservation(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Reservation{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *reservationRepoSQL) Find(ctx context.Context, filter *domain.FilterReservation) (result shareddomain.Reservation, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ReservationRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterReservation(globalshared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *reservationRepoSQL) Save(ctx context.Context, data *shareddomain.Reservation, updateOptions ...candishared.DBUpdateOptionFunc) <-chan error {
	output := make(chan error)
	go tracer.WithTracerFunc(ctx, "ReservationRepoSQL:Save", func(ctx context.Context, _ tracer.Tracer) {
		defer close(output)

		db := r.writeDB
		if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
			db = tx
		}

		data.UpdatedAt = time.Now()
		if data.CreatedAt.IsZero() {
			data.CreatedAt = time.Now()
		}
		if data.ID == 0 {
			output <- globalshared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
		} else {
			output <- globalshared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
		}

	})

	return output

	// trace, ctx := tracer.StartTraceWithContext(ctx, "ReservationRepoSQL:Save")
	// defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	// db := r.writeDB
	// if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
	// 	db = tx
	// }
	// data.UpdatedAt = time.Now()
	// if data.CreatedAt.IsZero() {
	// 	data.CreatedAt = time.Now()
	// }
	// if data.ID == 0 {
	// 	err = globalshared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	// } else {
	// 	err = globalshared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	// }
	// return
}

func (r *reservationRepoSQL) Delete(ctx context.Context, filter *domain.FilterReservation) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ReservationRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterReservation(globalshared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.Reservation{}).Error
	return
}

func (r *reservationRepoSQL) setFilterReservation(db *gorm.DB, filter *domain.FilterReservation) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
