// Code generated by candi v1.17.15.

package repository

import (
	"context"

	"monorepo/services/auth-service/internal/modules/token/domain"
	shareddomain "monorepo/services/auth-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// TokenRepository abstract interface
type TokenRepository interface {
	Find(ctx context.Context, filter *domain.FilterToken) (shareddomain.Token, error)
	Save(ctx context.Context, data *shareddomain.Token, updateOptions ...candishared.DBUpdateOptionFunc) error
}
