// Code generated by candi v1.17.15.

package usecase

import (
	"context"

	"monorepo/services/library-service/internal/modules/payment/domain"
	"monorepo/services/library-service/pkg/shared/repository"
	"monorepo/services/library-service/pkg/shared/usecase/common"

	"github.com/golangid/candi/codebase/factory/dependency"
)

// PaymentUsecase abstraction
type PaymentUsecase interface {
	GetAllPayment(ctx context.Context, filter *domain.FilterPayment) (data domain.ResponsePaymentList, err error)
	GetDetailPayment(ctx context.Context, id int) (data domain.ResponsePayment, err error)
	CreatePayment(ctx context.Context, data *domain.RequestTransaction) (err error) 
	UpdatePayment(ctx context.Context, data *domain.RequestPayment) (err error)
	DeletePayment(ctx context.Context, id int) (err error)
}

type paymentUsecaseImpl struct {
	deps          dependency.Dependency
	sharedUsecase common.Usecase
	repoSQL       repository.RepoSQL
	// repoMongo     repository.RepoMongo
}

// NewPaymentUsecase usecase impl constructor
func NewPaymentUsecase(deps dependency.Dependency) (PaymentUsecase, func(sharedUsecase common.Usecase)) {
	uc := &paymentUsecaseImpl{
		deps:    deps,
		repoSQL:   repository.GetSharedRepoSQL(),
		// repoMongo: repository.GetSharedRepoMongo(),
		
	}
	return uc, func(sharedUsecase common.Usecase) {
		uc.sharedUsecase = sharedUsecase
	}
}
