// Code generated by candi v1.17.15.

package repository

import (
	"context"

	shareddomain "monorepo/services/library-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
)

// LendingRepository abstract interface
type LendingRepository interface {
	FetchAll(ctx context.Context, filter *shareddomain.LendingParamGet) ([]shareddomain.Lending, error)
	Count(ctx context.Context, filter *shareddomain.LendingParamGet) int
	Find(ctx context.Context, filter *shareddomain.LendingParamGet) (shareddomain.Lending, error)
	Save(ctx context.Context, data *shareddomain.Lending, updateOptions ...candishared.DBUpdateOptionFunc) <-chan error
	Delete(ctx context.Context, filter *shareddomain.LendingParamGet) (err error)
}
