// Code generated by candi v1.17.15.

package repository

import (
	"context"

	"strings"
	"time"

	"monorepo/services/payment-service/internal/modules/payment/domain"
	shareddomain "monorepo/services/payment-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"monorepo/globalshared"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type paymentRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewPaymentRepoSQL mongo repo constructor
func NewPaymentRepoSQL(readDB, writeDB *gorm.DB) PaymentRepository {
	return &paymentRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *paymentRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterPayment) (data []shareddomain.Transaction, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "PaymentRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterPayment(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *paymentRepoSQL) Count(ctx context.Context, filter *domain.FilterPayment) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "PaymentRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterPayment(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Transaction{}).Count(&total)
	count = int(total)

	trace.Log("count", count)
	return
}

func (r *paymentRepoSQL) Find(ctx context.Context, filter *domain.FilterPayment) (result shareddomain.Transaction, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "PaymentRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterPayment(globalshared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *paymentRepoSQL) Save(ctx context.Context, data *shareddomain.Transaction, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "PaymentRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = globalshared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = globalshared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *paymentRepoSQL) Delete(ctx context.Context, filter *domain.FilterPayment) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "PaymentRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterPayment(globalshared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.Transaction{}).Error
	return
}

func (r *paymentRepoSQL) setFilterPayment(db *gorm.DB, filter *domain.FilterPayment) *gorm.DB {

	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}

func (r *paymentRepoSQL) SaveNotif(ctx context.Context, data *shareddomain.Transaction, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "PaymentRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = globalshared.SetSpanToGorm(ctx, db).Create(data).Error
	} else {
		err = globalshared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}
