// Code generated by candi v1.17.15.

package repository

import (
	"context"
	
	"time"
	"strings"

	"monorepo/services/library-service/internal/modules/activity/domain"
	shareddomain "monorepo/services/library-service/pkg/shared/domain"

	"github.com/golangid/candi/candishared"
	"github.com/golangid/candi/tracer"

	"monorepo/globalshared"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type activityRepoSQL struct {
	readDB, writeDB *gorm.DB
	updateTools     *candishared.DBUpdateTools
}

// NewActivityRepoSQL mongo repo constructor
func NewActivityRepoSQL(readDB, writeDB *gorm.DB) ActivityRepository {
	return &activityRepoSQL{
		readDB: readDB, writeDB: writeDB,
		updateTools: &candishared.DBUpdateTools{
			KeyExtractorFunc: candishared.DBUpdateGORMExtractorKey, IgnoredFields: []string{"id"},
		},
	}
}

func (r *activityRepoSQL) FetchAll(ctx context.Context, filter *domain.FilterActivity) (data []shareddomain.Activity, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoSQL:FetchAll")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	if filter.OrderBy == "" {
		filter.OrderBy = "updated_at"
	}

	db := r.setFilterActivity(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Order(clause.OrderByColumn{
		Column: clause.Column{Name: filter.OrderBy},
		Desc:   strings.ToUpper(filter.Sort) == "DESC",
	})
	if filter.Limit > 0 || !filter.ShowAll {
		db = db.Limit(filter.Limit).Offset(filter.CalculateOffset())
	}
	err = db.Find(&data).Error
	return
}

func (r *activityRepoSQL) Count(ctx context.Context, filter *domain.FilterActivity) (count int) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoSQL:Count")
	defer trace.Finish()

	var total int64
	r.setFilterActivity(globalshared.SetSpanToGorm(ctx, r.readDB), filter).Model(&shareddomain.Activity{}).Count(&total)
	count = int(total)
	
	trace.Log("count", count)
	return
}

func (r *activityRepoSQL) Find(ctx context.Context, filter *domain.FilterActivity) (result shareddomain.Activity, err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoSQL:Find")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	err = r.setFilterActivity(globalshared.SetSpanToGorm(ctx, r.readDB), filter).First(&result).Error
	return
}

func (r *activityRepoSQL) Save(ctx context.Context, data *shareddomain.Activity, updateOptions ...candishared.DBUpdateOptionFunc) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoSQL:Save")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	data.UpdatedAt = time.Now()
	if data.CreatedAt.IsZero() {
		data.CreatedAt = time.Now()
	}
	if data.ID == 0 {
		err = globalshared.SetSpanToGorm(ctx, db).Omit(clause.Associations).Create(data).Error
	} else {
		err = globalshared.SetSpanToGorm(ctx, db).Model(data).Omit(clause.Associations).Updates(r.updateTools.ToMap(data, updateOptions...)).Error
	}
	return
}

func (r *activityRepoSQL) Delete(ctx context.Context, filter *domain.FilterActivity) (err error) {
	trace, ctx := tracer.StartTraceWithContext(ctx, "ActivityRepoSQL:Delete")
	defer func() { trace.Finish(tracer.FinishWithError(err)) }()

	db := r.writeDB
	if tx, ok := candishared.GetValueFromContext(ctx, candishared.ContextKeySQLTransaction).(*gorm.DB); ok {
		db = tx
	}
	err = r.setFilterActivity(globalshared.SetSpanToGorm(ctx, db), filter).Delete(&shareddomain.Activity{}).Error
	return
}

func (r *activityRepoSQL) setFilterActivity(db *gorm.DB, filter *domain.FilterActivity) *gorm.DB {
	
	if filter.ID != nil {
		db = db.Where("id = ?", *filter.ID)
	}
	if filter.Search != "" {
		db = db.Where("(field ILIKE '%%' || ? || '%%')", filter.Search)
	}

	for _, preload := range filter.Preloads {
		db = db.Preload(preload)
	}

	return db
}
